### ISSUE TITLE
npm start运行后的问题，不知道这种是怎么解决

### ISSUE THREAD

**Issue by pingyaotianxia** [zxlfly/lunzi#6]
![image](https://user-images.githubusercontent.com/34472292/178886643-7fad34d0-c83f-490e-841c-fc5648172d9a.png)

(node:18196) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'mediaMetaInfo' of undefined
    at file:///D:/WorkSpace/lunzi/ffmpeg/src/index.js:76:43
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zxlfly** [comment]
这个是视频的信息是空的 没有获取到，如果参数没有问题的话，你得调试看看接口返回的数据是否有问题，之前也有人遇到过这个问题，如果你的代码不是最新的，可以拉下最新的代码。如果还不能解决，就只能调试看看啥原因导致获取信息为空，做个判断处理下，顺便提个pr修复下这个问题 @pingyaotianxia

**Comment by webbrain-one** [comment]
I've opened a pull request (https://github.com/zxlfly/lunzi/pull/8) to address the issue you're experiencing. 

The error occurs in `src/index.js` at line 76, where the code tries to access `mediaMetaInfo` from an undefined object. This typically happens when the expected data structure isn't properly initialized or the API response format has changed.

The PR adds proper null checking and error handling to prevent the `UnhandledPromiseRejectionWarning` and improve the stability of the application. It also implements better error handling patterns to catch potential undefined values before trying to access their properties.

Could you please review and test the changes? Let me know if you have any questions or suggestions!
